GET https://dummyjson.com/todos?limit=1 > examples/responses/1.json
Accept: application/json

--

POST https://dummyjson.com/todos/add > examples/responses/2.json
Content-Type: application/json

{
  "todo": "Use HTTPCli",
  "completed": true,
  "userId": 1
}